# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 19:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interior_num', models.CharField(blank=True, max_length=5, null=True, verbose_name='N\xfamero interior')),
                ('exterior_num', models.CharField(max_length=5, verbose_name='N\xfamero exterior')),
                ('street', models.CharField(max_length=100, verbose_name='Calle principal')),
                ('type_direction', models.CharField(help_text='Casa, trabajo, otro', max_length=10, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(db_index=True, max_length=100, verbose_name='C\xf3digo')),
                ('country_name', models.CharField(db_index=True, max_length=100, verbose_name='Pa\xeds')),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(db_index=True, max_length=100, verbose_name='Condado')),
            ],
            options={
                'verbose_name': 'Condado',
                'verbose_name_plural': 'Condados',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(db_index=True, max_length=100, verbose_name='Estado')),
                ('phone_prefix', models.CharField(blank=True, max_length=20, null=True, verbose_name='Prefijo de n\xfamero de tel\xe9fono')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Country', verbose_name='Pa\xeds')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='TownShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_name', models.CharField(db_index=True, max_length=100, verbose_name='Ciudad/Municipio')),
                ('zip_code', models.CharField(max_length=5, verbose_name='C\xf3digo postal')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.County', verbose_name='Condado')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
            },
        ),
        migrations.AddField(
            model_name='county',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.State', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='address',
            name='town_ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.TownShip', verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
